# Generated by Django 4.1.3 on 2022-11-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_player_is_staff_player_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="nickname",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
