# Generated by Django 4.1.3 on 2022-11-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="league",
            old_name="players",
            new_name="teams",
        ),
    ]
