# Generated by Django 4.1.3 on 2022-12-02 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_backdrop_path_alter_movie_poster_path"),
        ("users", "0001_initial"),
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="league",
            old_name="players",
            new_name="teams",
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=128)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="league.league"
                    ),
                ),
                ("movie_picks", models.ManyToManyField(to="movies.movie")),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.player"
                    ),
                ),
            ],
        ),
    ]
