# Generated by Django 4.1.3 on 2022-11-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_backdrop_path_alter_movie_poster_path"),
        ("users", "0001_initial"),
        ("league", "0002_rename_players_league_teams"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="league.league"
                    ),
                ),
                ("movie_picks", models.ManyToManyField(to="movies.movie")),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.player"
                    ),
                ),
            ],
        ),
    ]
