# Generated by Django 4.1.3 on 2022-11-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0003_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_name",
            field=models.CharField(default="demo", max_length=128),
            preserve_default=False,
        ),
    ]
