# Generated by Django 4.1.3 on 2022-11-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("title", models.CharField(max_length=256)),
                ("overview", models.TextField()),
                ("original_title", models.CharField(max_length=256)),
                ("original_language", models.CharField(max_length=32)),
                ("backdrop_path", models.CharField(max_length=256)),
                ("popularity", models.FloatField()),
                ("poster_path", models.CharField(max_length=256)),
                ("release_date", models.DateField()),
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
