# Generated by Django 4.1.3 on 2022-11-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="backdrop_path",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_path",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
